name: Build .NET Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v4

    - name: ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/aspnet-custom-font:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/aspnet-custom-font:latest